### PR TITLE
Update installation-and-setup.mdx

### PR DESCRIPTION
**Pull request by danieljcafonso**
That snippet is not the one we have on the router repo. not even sure where it came from

### CODE REVIEW

**Comment by atilafassina** [comment]
It was pointed out that this snippet throws warnings in a TypeScript code base, that's why a contributor added that runtime guards. So the snippet you deleted is fine, but it's using `<App>` instead of `<Router>`.

Removing the guard on `document.getElementById` makes TS sqwak because it may be `null`.

**Review by LadyBluenotes — APPROVED** [review]

**Comment by LadyBluenotes** [comment]
Oh shoot, does this mean we leave it? @atilafassina

**Comment by atilafassina** [comment]
> Oh shoot, does this mean we leave it? @atilafassina

@LadyBluenotes the runtime check that was deleted was not part of the problem, but it needs to use `<Router />` as @danieljcafonso changes do.

While we don't have a tab code-snippet component, I think it's best to have a snippet that works in both envs when possible.

**Comment by danieljcafonso** [comment]
> It was pointed out that this snippet throws warnings in a TypeScript code base, that's why a contributor added that runtime guards. So the snippet you deleted is fine, but it's using `<App>` instead of `<Router>`.
> 
> Removing the guard on `document.getElementById` makes TS sqwak because it may be `null`.

That is a lot of magic from a installation and setup guide. Imagining I would get here to figure how how do I add a Router and see this magic is very confusing.
Maybe we should add a note there 🤔 

Either way, right now if I move that App out of there and just put Router, TS will be okay and this should be clearer right?

**Comment by danieljcafonso** [comment]
Swapped App with Router

**Review by LadyBluenotes — APPROVED** [review]

**Pull request merged**
