### PR TITLE
feat: new search dialog

### PR DESCRIPTION
**Pull request by GiyoMoon**

### CODE REVIEW

**Review by LadyBluenotes — CHANGES_REQUESTED** [review]
Fantastic work with this, thank you so much!

Only thing I think that needs to be adjusted is the component on mobile. Looks like it's causing some overlap.

image

**Comment by GiyoMoon** [comment]
@LadyBluenotes good catch, fixed! 
image

**Review by LadyBluenotes — APPROVED** [review]

**Review by atilafassina — APPROVED** [review]
🏆 that's a very **solid** search input!!!

**Comment by stefan-karger** [comment]
Awesome work!
If I search for something that has lots of results the dialog overflows the screen.
grafik

Browser: Firefox

**Comment by femincan** [comment]
Good catch @sek-consulting. I experienced the same problem and solved it with dev tools, but because the search functionality doesn't work locally I can't make the changes.

The problem is caused by the `bottom` property of the dialog content. Because on larger screens `bottom` is `auto`, if the content is too long the search dialog overflows. The solution is replacing the `bottom` property with a fixed value like `56px` as the `top`.

**Comment by GiyoMoon** [comment]
Thanks for the feedback, made a small PR to fix this: #863

**Pull request merged**
